[package]
name = "neo-resampler"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
num = "0.4.3"

[dev-dependencies]
float-cmp = "0.10.0"
babycat = { version = "0.0.15" }
rand = "0.8.5"
criterion = "0.5.1"

[[bench]]
name = "resampling_benchmark"
harness = false
